name: Deploy API Gateway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ApiGateway/ApiGateway.csproj

      - name: Build and Publish
        run: dotnet publish ApiGateway/ApiGateway.csproj -c Release -o published

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "your-api-gateway-app-service"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: published
