name: Build Shared Library

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ShareLibrary/ShareLibrary.csproj

      - name: Build and Pack
        run: dotnet pack ShareLibrary/ShareLibrary.csproj -c Release -o published

      - name: Publish to NuGet
        run: dotnet nuget push published/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
